/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'scott.tomaszewski' at '5/17/14 11:40 PM' with Gradle 1.12
 *
 * @author scott.tomaszewski, @date 5/17/14 11:40 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
